In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
print(a)

[1 2 3 4 5]


In [4]:
type(a)

numpy.ndarray

In [6]:
a.shape

(5,)

In [18]:
b = np.array([[1, 2], [2, 4], [3, 8], [4, 0], [5, 22]])

In [19]:
# b.shape
print(b.shape, b)

(5, 2) [[ 1  2]
 [ 2  4]
 [ 3  8]
 [ 4  0]
 [ 5 22]]


In [20]:
b[0]

array([1, 2])

In [23]:
b[4][1] = 99

In [24]:
b

array([[ 1,  2],
       [ 2,  4],
       [ 3,  8],
       [ 4,  0],
       [ 5, 99]])

In [25]:
a = np.zeros((3, 3))

In [26]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
b = np.ones((3,3), dtype = 'int32')

In [33]:
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [30]:
b.dtype

dtype('float64')

In [35]:
np.zeros?

In [37]:
c = np.full((2, 3), 5)

In [39]:
print(c, c.shape)

[[5 5 5]
 [5 5 5]] (2, 3)


In [54]:
eye = np.eye(4, dtype = np.int64)

In [55]:
eye

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [56]:
random_matrix = np.random.random((4, 3))

In [57]:
random_matrix

array([[0.9095907 , 0.46502755, 0.9250652 ],
       [0.64460316, 0.30291203, 0.77543335],
       [0.80114071, 0.75525663, 0.20091748],
       [0.55537445, 0.00839432, 0.41292695]])

In [58]:
print(random_matrix[:, 2])

[0.9250652  0.77543335 0.20091748 0.41292695]


In [62]:
# Mathematical operations in numpy

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x, y)
print(x.shape, y.shape)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
(2, 2) (2, 2)


In [64]:
print(x+y, np.add(x, y))

[[ 6  8]
 [10 12]] [[ 6  8]
 [10 12]]


In [65]:
print(x-y, np.subtract(x, y))

[[-4 -4]
 [-4 -4]] [[-4 -4]
 [-4 -4]]


In [67]:
print(x*y, np.multiply(x, y))

[[ 5 12]
 [21 32]] [[ 5 12]
 [21 32]]


In [68]:
print(x/y, np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]] [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [70]:
print(np.sqrt(x), np.sqrt(y))

[[1.         1.41421356]
 [1.73205081 2.        ]] [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [72]:
print(x.dot(y), np.dot(x, y))

[[19 22]
 [43 50]] [[19 22]
 [43 50]]


In [77]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [75]:
print(sum(a), np.sum(a))

15 15


In [79]:
a.shape

(2, 5)

In [81]:
print(np.sum(a, axis = 1))

[15 40]


In [95]:
a = np.array([1,2,3,4,5, 6])
b = np.array([1,2,3,4,5, 6])
b = b**2

In [96]:
b

array([ 1,  4,  9, 16, 25, 36])

In [97]:
stacked = np.stack((a, b), axis = 0)

In [98]:
stacked

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  4,  9, 16, 25, 36]])

In [99]:
stacked.shape

(2, 6)

In [110]:
stacked.reshape((-1,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  4,  9, 16, 25, 36]])

In [116]:
a = np.arange(10) + 1
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [123]:
a = np.random.rand?
print(a)

[[-1.47743302  1.20601062 -0.37230766]
 [ 0.48343472 -0.94372465 -1.02462542]]


In [121]:
a = np.random.randn(2, 3)
print(a)

[[-1.47743302  1.20601062 -0.37230766]
 [ 0.48343472 -0.94372465 -1.02462542]]


In [144]:
b = np.random.randint(5, 100, 50)

In [145]:
len(list(set(b)))

43

In [148]:
#Choice between numbers or array of numbers

a = np.random.choice(b, size = 30, replace = True)
print(a)

[28 90 69 19 95 48 62 21 98 90 13 58 20 75 19 60 75 60 21 96 29 13 28 69
 39 25 59 24 24 53]


In [163]:
np.random.seed(1)
rand_int = np.random.randint(1, 1000, 100)

In [164]:
print(rand_int)

[ 38 236 909  73 768 906 716 646 848 961 145 130 973 584 750 509 391 282
 179 277 255 358 915 469 908 253 491 669 926 399 563 581 216 984 754 504
 479 865  87 142 394   8 320 830 535 314 514 897 317 210 265 729 654 628
 432 634 457 543  72 388 455 918 562 314 516 965 793 498  44 589  27 821
 337 622 884 298 467  16  65 197  26 368 739 472 904 283 666 617  23 778
 708 127 280 382 357 156 934 314 596 167]


In [168]:
rand_int = rand_int.reshape(-1, 2)
print(rand_int.shape)

(50, 2)


In [170]:
print(rand_int)

[[ 38 236]
 [909  73]
 [768 906]
 [716 646]
 [848 961]
 [145 130]
 [973 584]
 [750 509]
 [391 282]
 [179 277]
 [255 358]
 [915 469]
 [908 253]
 [491 669]
 [926 399]
 [563 581]
 [216 984]
 [754 504]
 [479 865]
 [ 87 142]
 [394   8]
 [320 830]
 [535 314]
 [514 897]
 [317 210]
 [265 729]
 [654 628]
 [432 634]
 [457 543]
 [ 72 388]
 [455 918]
 [562 314]
 [516 965]
 [793 498]
 [ 44 589]
 [ 27 821]
 [337 622]
 [884 298]
 [467  16]
 [ 65 197]
 [ 26 368]
 [739 472]
 [904 283]
 [666 617]
 [ 23 778]
 [708 127]
 [280 382]
 [357 156]
 [934 314]
 [596 167]]


In [180]:
print(np.min(rand_int, axis = 0))

[23  8]


In [174]:
print(np.max(rand_int, axis = 1))

[236 909 906 716 961 145 973 750 391 277 358 915 908 669 926 581 984 754
 865 142 394 830 535 897 317 729 654 634 543 388 918 562 965 793 589 821
 622 884 467 197 368 739 904 666 778 708 382 357 934 596]


In [177]:
print(np.mean(rand_int))

485.65


In [179]:
print(np.mean(rand_int, axis = 1))

[137.  491.  837.  681.  904.5 137.5 778.5 629.5 336.5 228.  306.5 692.
 580.5 580.  662.5 572.  600.  629.  672.  114.5 201.  575.  424.5 705.5
 263.5 497.  641.  533.  500.  230.  686.5 438.  740.5 645.5 316.5 424.
 479.5 591.  241.5 131.  197.  605.5 593.5 641.5 400.5 417.5 331.  256.5
 624.  381.5]


In [194]:
rand_int = rand_int.reshape(-1, )

In [197]:
rand_int

array([ 38, 236, 909,  73, 768, 906, 716, 646, 848, 961, 145, 130, 973,
       584, 750, 509, 391, 282, 179, 277, 255, 358, 915, 469, 908, 253,
       491, 669, 926, 399, 563, 581, 216, 984, 754, 504, 479, 865,  87,
       142, 394,   8, 320, 830, 535, 314, 514, 897, 317, 210, 265, 729,
       654, 628, 432, 634, 457, 543,  72, 388, 455, 918, 562, 314, 516,
       965, 793, 498,  44, 589,  27, 821, 337, 622, 884, 298, 467,  16,
        65, 197,  26, 368, 739, 472, 904, 283, 666, 617,  23, 778, 708,
       127, 280, 382, 357, 156, 934, 314, 596, 167])

In [189]:
print(np.median(rand_int))

475.5


In [190]:
print(sum(rand_int)/len(rand_int))

[485.65]


In [192]:
weights = np.arange(100) + 1
# print(weights)

In [196]:
#weighted mean
print(np.average(rand_int, weights=weights))

464.10534653465345


In [198]:
u = np.mean(rand_int)

In [199]:
std_dev = np.sqrt(np.mean(abs(rand_int - u)**2))

In [200]:
std_dev

282.9695522490008

In [201]:
std_dev = np.std(rand_int)
print(std_dev)

282.9695522490008


In [202]:
print(std_dev**2, np.var(rand_int))

80071.76749999999 80071.76749999999


In [207]:
rand_int = list(rand_int)
print(len(rand_int))

100


In [208]:
len(set(rand_int))

98