In [ ]:
import torch

In [ ]:
torch.__version__

'1.12.1+cu113'

In [ ]:
#Pytorch supports 
# FloatTensor: 32 bit float
# DoubleTensor: 64 bit float
# Halftensor: 16 bit float
# IntTensor: 32 bit int
# LongTensor: 64 bit int

In [ ]:
import numpy as np

In [ ]:
a = np.array(1)

b = torch.tensor(1)

print(a)
print(b)

1
tensor(1)


In [ ]:
print(type(a), type(b))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [ ]:
a = torch.tensor(2)
b = torch.tensor(1)

In [ ]:
print(a, b)

tensor(2) tensor(1)


In [ ]:
print(a+b)

tensor(3)


In [ ]:
print(b-a)

tensor(-1)


In [ ]:
print(a*b, a/b)

tensor(2) tensor(2.)


In [ ]:
a = np.array(2)
b = np.array(1)

In [ ]:
print(a+b, b-a, a*b, a/b)

3 -1 2 2.0


In [ ]:
a = np.zeros((3, 3))
print(a, a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)


In [ ]:
a = torch.zeros((3, 3))
print(a, a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) torch.Size([3, 3])


In [ ]:
np.random.seed(42)

a = np.random.randn(3, 3)
print(a)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]


In [ ]:
torch.manual_seed(42)

a = torch.randn(3, 3)
print(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


In [ ]:
np.random.seed(42)

a = np.random.randn(3, 3)
b = np.random.randn(3, 3)
print(a)
print(b)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]
[[ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733]]


In [ ]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.dot(a,b))
print(np.divide(a,b))
print(np.transpose(a))

[[ 1.0392742  -0.60168199  0.18195878]
 [ 1.76499213 -2.14743362 -1.95905479]
 [ 1.01692529 -0.24539639 -0.15522705]]
[[-0.04584589  0.32515339  1.11341829]
 [ 1.28106758  1.67912687  1.49078088]
 [ 2.14150034  1.78026585 -0.78372172]]
[[-0.12814468 -0.62164688  0.21069439]
 [ 0.90133115 -0.02065676 -0.3790019 ]
 [ 1.30648762 -1.7246546  -2.20677932]]
[[ 0.9155008   0.29835784 -1.39069607]
 [ 6.29449313  0.12238321  0.13573803]
 [-2.80855031 -0.75771243 -1.49396459]]
[[ 0.49671415  1.52302986  1.57921282]
 [-0.1382643  -0.23415337  0.76743473]
 [ 0.64768854 -0.23413696 -0.46947439]]


In [ ]:
torch.manual_seed(42)

a = torch.randn(3, 3)
b = torch.randn(3, 3)
print(a, b)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]])


In [ ]:
print(torch.add(a, b))
print(torch.sub(a, b))
print(torch.mm(a,b))
print(torch.div(a,b))
print(torch.t(a))

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])
tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])
tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])
tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])
tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])


In [ ]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[5, 6], [7, 8]])

In [ ]:
print(a, b)

tensor([[1, 2],
        [3, 4]]) tensor([[5, 6],
        [7, 8]])


In [ ]:
print(torch.cat((a, b), dim=1))

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [ ]:
a = torch.cat((a, b), dim=1)

In [ ]:
a = a.reshape(1, 8)

In [ ]:
a

tensor([[1, 2, 5, 6, 3, 4, 7, 8]])

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
tensor = torch.from_numpy(a)
print(tensor)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [ ]:
a = torch.ones((2, 2), requires_grad = True)

In [ ]:
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
b = a+5
c = b.mean()
print(b, c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


In [ ]:
c.backward()

print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
